### ISSUE TITLE
BRDF correction (image_correct.py), ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by arthur-e** [EnSpec/hytools#18]
I'm encountering a `ValueError` when running the `scripts/image_correct.py` workflow with an AVIRIS Classic L2 surface reflectance image:

```
f180621t01p00r16_corr_v1k1_img.bin
f180621t01p00r16_corr_v1k1_img.hdr
```

[Downloaded from this collection on NASA Earthdata Search](https://search.earthdata.nasa.gov/search/granules?p=C2711871294-ORNL_CLOUD); see also [this DOI.](	https://doi.org/10.3334/ORNLDAAC/2154)

The configuration file is attached here:

- [`f180621t01p00r16_corr_v1k1_img_BRDF_correction.config`](https://github.com/user-attachments/files/18270867/f180621t01p00r16_corr_v1k1_img_BRDF_correction.config.json)

```sh
$ python scripts/image_correct.py f180621t01p00r16_corr_v1k1_img_BRDF_correction.config
```
```python
Traceback (most recent call last):
  File "/usr/local/dev/hytools/scripts/image_correct.py", line 162, in <module>
    main()
  File "/usr/local/dev/hytools/scripts/image_correct.py", line 48, in main
    calc_brdf_coeffs(actors,config_dict)
  File "/usr/local/python-env/hytools/lib/python3.10/site-packages/hy_tools-1.5.0-py3.10.egg/hytools/brdf/brdf.py", line 65, in calc_brdf_coeffs
  File "/usr/local/python-env/hytools/lib/python3.10/site-packages/ray-2.39.0-py3.10-linux-x86_64.egg/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/python-env/hytools/lib/python3.10/site-packages/ray-2.39.0-py3.10-linux-x86_64.egg/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python-env/hytools/lib/python3.10/site-packages/ray-2.39.0-py3.10-linux-x86_64.egg/ray/_private/worker.py", line 2753, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/usr/local/python-env/hytools/lib/python3.10/site-packages/ray-2.39.0-py3.10-linux-x86_64.egg/ray/_private/worker.py", line 904, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::HyTools.gen_mask() (pid=47163, ip=10.8.202.11, actor_id=1ee24923e0efc2d27f98be8c01000000, repr=<hytools.base.HyTools object at 0x719a307b0370>)
  File "/usr/local/dev/hytools/hytools/base.py", line 490, in gen_mask
    self.mask[name] = masker(self,args)
  File "/usr/local/dev/hytools/hytools/masks/masks.py", line 40, in mask_create
    mask &= mask_dict[mask_name](hy_obj,args)
  File "/usr/local/dev/hytools/hytools/masks/calc_apply.py", line 72, in cloud
    mask = ~zhai_cloud(hy_obj,args['cloud'],args['shadow'],
  File "/usr/local/dev/hytools/hytools/masks/cloud.py", line 83, in zhai_cloud
    T2 = np.mean(CI_2[hy_obj.mask['no_data']]) + t2*(np.max(CI_2[hy_obj.mask['no_data']])-np.mean(CI_2[hy_obj.mask['no_data']]))
  File "/usr/local/python-env/hytools/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/usr/local/python-env/hytools/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

This is run with:

```
hy-tools==1.5.0
ray==2.39.0
```

Any suggestions are appreciated. This workflow has worked just fine with other AVIRIS Classic scenes from the same collection.

**Comment by oldmanye007** [comment]
Laterally, that error means `hy_obj.mask['no_data']` does not return a proper nodata mask. Please check if nodata value is corrected parsed.

However, there is a more critical problem in the configuration file, which is no L1 ancillary file is provided. BRDF correction cannot be implemented with L2 reflectance data alone. The file path here should point to the L1 ancillary file.
```
         "path_length": [
            "/media/arthur-e/Mimisbrunnr/AVIRIS/f180621t01p00r16_corr_v1k1_img.bin",
            0
         ],
         ... ...
```

L1 ancillary file (named with *obs_ort) can be found as "AVIRIS-Classic: L1B Calibrated Radiance, Facility Instrument Collection, V1" from DAAC or from this [link](https://popo.jpl.nasa.gov/avcl/y18_data/f180621t01p00r16.tar.gz)
The path of the obs_ort file should be placed inside "anc_files" of the config file. You can refer to the [sample config file ](https://github.com/EnSpec/hytools/blob/master/examples/configs/brdf_glint_correct_config.json)

**Comment by oldmanye007** [comment]
L1 ancillary file (named with ***obs_ort**)  should be used in the config as well. More details are provided in my another comment.

> The configuration file is attached here:
> 
> * [`f180621t01p00r16_corr_v1k1_img_BRDF_correction.config`](https://github.com/user-attachments/files/18270867/f180621t01p00r16_corr_v1k1_img_BRDF_correction.config.json)
>

**Comment by arthur-e** [comment]
Thanks for this information. However, I'm getting the same error after pointing the `"path_length"` to this file.

Here's an updated configuration file, but for a second flight line that is resulting in the same error:

- [f180622t01p00r06_corr_v1k1_img_BRDF_correction.config](https://github.com/user-attachments/files/18286229/f180622t01p00r06_corr_v1k1_img_BRDF_correction.config.json)

**Perhaps one of the other `"anc_files"` entries needs to also point to this or another L1B file?** [The sample configuration file](https://github.com/EnSpec/hytools/blob/master/examples/configs/brdf_glint_correct_config.json) you pointed to, however, has all these entries pointing to the same file.

A minor note: Since I'm not interested in the L1B data, besides the ancillary file, I was relieved to find that it can also be downloaded directly from Earthdata Search, in [the "AVIRIS-Classic: L1B Calibrated Radiance, Facility Instrument Collection, V1" collection](https://search.earthdata.nasa.gov/search/granules/collection-details?p=C2714723060-ORNL_CLOUD). That is, instead of downloading the entire L1B archive for a flight line, individual files within that archive can be downloaded by searching for the granule ID and a filename stub ("obs_ort").

**Comment by oldmanye007** [comment]
Yes, replacing all paths of each layer in "anc_files" is what I meant. It
is good to have an option to just download the obs_ort file.

**Comment by oldmanye007** [comment]
To fix the error, the first step is to figure out what the NoData value
actually is in the reflectance image. Then, we need to know whether HyTools
gets the right Nodata value after loading the image. The simple way is to
look at the values in the array `hy_obj.mask['no_data']`.

**Comment by arthur-e** [comment]
Incidentally, since adding the ancillary file (for all `"anc_files"` keys), I see an additional message in the terminal while `image_correct.py` is running:

```sh
(HyTools pid=35687) Reflectance and ancillary no data extents do not match, combining no data masks.
```

The ancillary file should be the correct one for this flight line:

```
...
   "input_files": [
      "/media/arthur-e/Mimisbrunnr/AVIRIS/f180621t01p00r16_corr_v1k1_img.bin"
   ],
   "anc_files": {
      "/media/arthur-e/Mimisbrunnr/AVIRIS/f180621t01p00r16_corr_v1k1_img.bin": {
         "path_length": [
            "/media/arthur-e/Mimisbrunnr/AVIRIS/f180621t01p00r16rdn_e_obs_ort",
            0
         ],
         "sensor_az": [
            "/media/arthur-e/Mimisbrunnr/AVIRIS/f180621t01p00r16rdn_e_obs_ort",
            1
         ],
...
```

Using `ipdb`, I determined that:

```python
>>> hy_obj.mask['no_data'].any()
False
```

If I [set a breakpoint here,](https://github.com/EnSpec/hytools/blob/5a837ce76fad81737e81d0336a869dd01fec3cb5/hytools/base.py#L102) instead:

```python
>>> self.mask['no_data'].any()
False

>>> ancillary.mask['no_data'].any()
True

>>> self.mask['no_data'].shape == ancillary.mask['no_data'].shape
True
```

Part of the problem may be that the NoData value is `-0.0`, which doesn't seem valid:

```python
>>> self.no_data
-0.0
```

This seems to be a consequence of the fact that the header file, or `*.hdr` file, does not have a `"data ignore value"` defined. [(See corresponding code where ENVI files are read-in.)](https://github.com/EnSpec/hytools/blob/master/hytools/io/envi.py#L128)

Here's the header file (downloaded from Earthdata Search) for one of these granules:
- [f180622t01p00r06_corr_v1k1_img.hdr](https://github.com/user-attachments/files/18286720/f180622t01p00r06_corr_v1k1_img.hdr.txt)

**Comment by oldmanye007** [comment]
If 'data ignore value' is not found in the header file, None will be
returned, and the following lines will try to figure that out.
Basically, the four corners of Band1 will be used to guess the Nodata
value.
https://github.com/EnSpec/hytools/blob/5a837ce76fad81737e81d0336a869dd01fec3cb5/hytools/io/envi.py#L151-L179

A quick way to test is to read the corners and find out what has been
identified as Nodata.
If you follow basic usage (the
https://github.com/EnSpec/hytools/tree/master?tab=readme-ov-file#basic-usage),
You can try to get the pixel values with
pixels = hy_obj.get_pixels([0,0],[0,-1],[-1,-1],[-1,0])
and Nodata as well
hy_obj.no_data

**Comment by oldmanye007** [comment]
Finally got a chance to download the huge L2 reflectance file, and it
is actually a file that exemplifies the inconsistency of the
AVIRIS-Classic archive.
First, pixels in the first two bands are all 0, which we cannot use to
identify nodata value.
Second, the nodata value is supposed to be -0.9999, while the actual
value is -0.9999*smoothing_factor. Smoothing_factors are band-by-band
values that are stored in the header for a reason.

There are ways to work around that, please check out the branch to
test (https://github.com/EnSpec/hytools/tree/netcdf_grouptopo_chtc)

**Comment by arthur-e** [comment]
Adding a `data ignore value` (NoData value) to the L2 header file solved the problem. It's unfortunate that it wasn't included in the file to begin with.

It seems the NoData value for these granules is `-0.9999`, which makes me wonder if there is also a scaling issue with these files, as `-9999` is a more typical choice.
